### ISSUE TITLE
how to calculate current  live segment

### ISSUE THREAD

**Issue by invisiblecoder99** [unki2aut/go-mpd#4]
how to calculate current  live segment cause when am  choosing start number its giving 1  hour behind its not giving  live

**Comment by unki2aut** [comment]
This library only parses the DASH manifest into a data structure but it doesn't interpret it.

How to calculate segment availability can be found in section `5.3.9.5.3 Media Segment information` of the DASH standard.

@quickstreamingmedia what type of manifest are we talking about? Maybe you can post an example so I can help you further.

**Comment by invisiblecoder99** [comment]
$number$ it uses dynamic playlist

**Comment by invisiblecoder99** [comment]
@unki2aut https://pastebin.com/Q6Bbpw3n can you tell me how to get latest segment according to client clock

**Comment by unki2aut** [comment]
@quickstreamingmedia you do have a `SegmentTimeline` MPD and the calculation here is simple as the `S` tag defines how many segments are currently available.

So for representation `1` there are 1 + 453 = 454 segments available with segment numbers ranging from `36279284` to `36279737` with a duration of 200 / 25 (`S.d` /  `timescale`) = 8 seconds.

If the MPD is found at location `http://example.com/my-video/main.mpd` the URL of the last segment for representation `1` would be `http://example.com/my-video/1460881_video_1_0_36279737.mp4?m=1612386835`.

Also be aware that this is a live stream (indicated by `MPD.type = "dynamic"`) and as written in `minimumUpdatePeriod` has to be updated every 30 seconds. Usually such streams have a moving window of available segments so after the MPD update the first segment might be `36279288`. But it's uncommon that the `minimumUpdatePeriod` and segment duration differ as one always wants to get the latest segment as fast as possible.

**Comment by invisiblecoder99** [comment]
When I use startNumber +S@r am getting 404 there must be some formula which calculate according to time. Can you help me finding that I tried a lot but it does not workout @unki2aut

**Comment by unki2aut** [comment]
@quickstreamingmedia if can you post the URL to the manifest, I can investigate.
Also a good source for help is the https://video-dev.slack.com/ Slack channel 🙂

**Comment by invisiblecoder99** [comment]
You need to add me to that workspace

**Comment by invisiblecoder99** [comment]
Am done with it

**Comment by invisiblecoder99** [comment]
This is not solved now segment timeline for video issue

**Comment by invisiblecoder99** [comment]
https://github.com/unki2aut/go-mpd/blob/feature/merge-mpds/mpd.go  does this branch code gives a way to use segment timelines in mpd ??

 i am able to get video but audio for timeline   this could help ??

**Comment by unki2aut** [comment]
@quickstreamingmedia this library only extends the [GoLang XML unmarshalling](https://golang.org/pkg/encoding/xml/#Unmarshal) with DASH specific structs and parsing of duration and timestamp properties, but it doesn't help you to interpret the data in those structs.

Please have a look at the [ISO/IEC 23009-1 DASH standard](https://www.iso.org/standard/65274.html) or ask in the `video-dev` Slack channel for its interpretation [as written above](https://github.com/unki2aut/go-mpd/issues/4#issuecomment-808869875).
